# What is NumPy?

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries.

Install this package in the commant prompt

 - conda install numpy

we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices,and number generation. 

In [1]:
import numpy as np

# Numpy Arrays

Numpy arrays essentially come in two: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).



## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [2,4,6,8,10]
my_list

[2, 4, 6, 8, 10]

In [3]:
np.array(my_list)

array([ 2,  4,  6,  8, 10])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in methods to generate arrays


### arange

Return evenly spaced values within a given interval.

In [6]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### zeros and ones

Generate arrays of zeros or ones

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval. 

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### 1. rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [17]:
np.random.rand(2)

array([0.15425512, 0.46196657])

In [22]:
np.random.rand(5,4)

array([[0.08320719, 0.58577321, 0.48546293, 0.28971118],
       [0.6216065 , 0.01686073, 0.39173586, 0.62120894],
       [0.77034605, 0.20971744, 0.32936018, 0.5420914 ],
       [0.64523522, 0.36666536, 0.79717623, 0.7829081 ],
       [0.1860463 , 0.98018665, 0.62527795, 0.89615008]])

### 2. randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [23]:
np.random.randn(2)

array([ 1.28891282, -1.44439516])

In [26]:
np.random.randn(5,4)

array([[ 0.96586362, -0.51498915,  2.51691747, -0.04485899],
       [ 0.30923055, -0.28092116,  1.1595066 ,  1.316518  ],
       [ 0.74584517,  1.21128995, -0.4109176 ,  1.26651458],
       [ 0.15823805,  0.53567562, -0.33684556,  0.74253664],
       [-0.30443797, -1.04251264, -0.78205991,  1.78253842]])

### 3. randint
Return random integers from low (inclusive) to high (exclusive).

In [27]:
np.random.randint(1,100)

26

In [29]:
np.random.randint(1,100,10)

array([44, 64, 55, 29, 97, 18,  7, 84, 87, 70])

## Array Attributes and Methods 

In [57]:
arr = np.arange(30)
ranarr = np.random.randint(0,50,5)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [59]:
ranarr

array([ 9, 10, 29,  1, 28])

## Reshape
Returns an array containing the same data with a new shape. 

In [60]:
arr.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### max, min, argmax, argmin

For finding max or min values. Or to find their index locations using argmin or argmax

In [61]:
ranarr

array([ 9, 10, 29,  1, 28])

In [62]:
ranarr.max()

29

In [63]:
ranarr.argmax()

2

In [64]:
ranarr.min()

1

In [65]:
ranarr.argmin()

3

## Shape

Shape is an attribute that arrays have (not a method):

In [66]:
# Vector
arr.shape

(30,)

In [68]:
# Note the two sets of brackets

arr.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [69]:
arr.reshape(1,30).shape

(1, 30)

In [70]:
arr.reshape(30,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [71]:
arr.reshape(30,1).shape

(30, 1)

### dtype

Find the data type of the object in the array:

In [72]:
arr.dtype

dtype('int64')