# NumPy Indexing and Selection

In [1]:
import numpy as np

In [40]:
#Creating sample array
arr = np.arange(0,21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

## Bracket Indexing and Selection

very similar to lists

In [41]:
arr[8]

8

In [42]:
arr[1:9]

array([1, 2, 3, 4, 5, 6, 7, 8])

## Broadcasting

Numpy arrays differ from a list because of their ability to broadcast:

In [43]:
#Setting a value with index range (Broadcasting)
arr[0:5]=50
arr

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [44]:
arr = np.arange(0,21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [45]:
slice_of_arr = arr[0:11]

slice_of_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
slice_of_arr[:]=99

slice_of_arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [47]:
arr
# changes in our original array too

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [48]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

# Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**.

In [56]:
arr_2d = np.array(([10,20,30],[40,50,60],[70,80,90]))

arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [57]:
arr_2d[2]

array([70, 80, 90])

In [58]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][2]

60

In [59]:
# same as above
arr_2d[1,2]

60

In [60]:
# Array slicing
#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[20, 30],
       [50, 60]])

In [61]:
#Shape bottom row
arr_2d[2]

array([70, 80, 90])

In [62]:
# Same as above
arr_2d[2,:]

array([70, 80, 90])

In [64]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [66]:
arr_length = arr2d.shape[1]
arr_length

10

In [67]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [70]:
arr2d[[2,4,6,8,9]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [72]:
arr2d[[8,2,9,3]]
# option for any order

array([[8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

## Selection

Use brackets for selection based off of comparison operators.

In [74]:
arr = np.arange(3,15)
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [76]:
arr > 6

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True])

In [78]:
bool_arr = arr>6
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True])

In [79]:
arr[bool_arr]

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [80]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [81]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Operations

## Arithmetic


In [83]:
arr = np.arange(0,15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [84]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [86]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [88]:
arr / arr

/Users/kirandarshak/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.])

In [89]:
2/arr

/Users/kirandarshak/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 2.        , 1.        , 0.66666667, 0.5       ,
       0.4       , 0.33333333, 0.28571429, 0.25      , 0.22222222,
       0.2       , 0.18181818, 0.16666667, 0.15384615, 0.14285714])

In [91]:
arr ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744])

## Universal Array Functions

In [92]:
# Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [93]:
# exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06])

In [94]:
np.max(arr) 

# same as arr.max()

14

In [95]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722])

In [96]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736])

In [97]:
np.log(arr)

/Users/kirandarshak/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733])